### ISSUE TITLE
The Autodiscover service couldn't be located.

### ISSUE THREAD

**Issue by mayankdonbosco** [Microsoft/mail2bug#68] opened 2017-05-29 09:43 UTC
I was trying to setup Mail 2 Bug Service.  Once i run the service, it given me error that autodiscover service couldnot be loaded. 

C:\Users\mapar\Desktop\MAIL2BUG\Service>Mail2Bug.exe
2017-05-29 14:53:19,765 [1] INFO  Mail2Bug.MainApp [(null)] - Initializing engine for instance 'STCI Email Extraction Customer DSAT' (Persistent? True)
2017-05-29 14:53:19,794 [1] INFO  Mail2Bug.Mail2BugEngine [(null)] - Initalizing MailboxManager
2017-05-29 14:53:19,812 [1] INFO  Mail2Bug.Helpers.DPAPIHelper [(null)] - Reading encrypted data from file .\Resources\mail2bug.bin
2017-05-29 14:53:19,825 [1] INFO  Mail2Bug.Email.EWS.EWSConnectionManger [(null)] - Creating FolderMailboxManager for (mapar@microsoft.com, FAREAST\mapar, -485684100, False)
2017-05-29 14:53:48,873 [1] ERROR Mail2Bug.MainApp [(null)] - Exception while initializing instance 'STCI Email Extraction Customer DSAT'
Microsoft.Exchange.WebServices.Data.AutodiscoverLocalException**: **The Autodiscover service couldn't be located.****
   at Microsoft.Exchange.WebServices.Autodiscover.AutodiscoverService.InternalGetLegacyUserSettings[TSettings](String emailAddress, List`1 redirectionEmailAddresses, Int32& currentHop)
   at Microsoft.Exchange.WebServices.Autodiscover.AutodiscoverService.InternalGetLegacyUserSettings[TSettings](String emailAddress, List`1 redirectionEmailAddresses, Int32& currentHop)
   at Microsoft.Exchange.WebServices.Autodiscover.AutodiscoverService.InternalGetLegacyUserSettings[TSettings](String emailAddress, List`1 redirectionEmailAddresses, Int32& currentHop)
   at Microsoft.Exchange.WebServices.Autodiscover.AutodiscoverService.GetLegacyUserSettings[TSettings](String emailAddress)
   at Microsoft.Exchange.WebServices.Autodiscover.AutodiscoverService.InternalGetLegacyUserSettings(String emailAddress, List`1 requestedSettings)
   at Microsoft.Exchange.WebServices.Autodiscover.AutodiscoverService.GetUserSettings(String userSmtpAddress, UserSettingName[] userSettingNames)
   at Microsoft.Exchange.WebServices.Data.ExchangeService.GetAutodiscoverUrl(String emailAddress, ExchangeVersion requestedServerVersion, AutodiscoverRedirectionUrlValidationCallback validateRedirectionUrlCallback)
   at Microsoft.Exchange.WebServices.Data.ExchangeService.AutodiscoverUrl(String emailAddress, AutodiscoverRedirectionUrlValidationCallback validateRedirectionUrlCallback)
   at Mail2Bug.Email.EWS.EWSConnectionManger.ConnectToEWS(Credentials credentials, Boolean useConversationGuidOnly) in C:\Users\mapar\Desktop\MAIL2BUG\Mail_2_Bug_Repo\mail2bug\Mail2Bug\Email\EWS\EWSConnectionManger.cs:line 91
   at Mail2Bug.Email.EWS.EWSConnectionManger.GetConnection(Credentials credentials, Boolean useConversationGuidOnly) in C:\Users\mapar\Desktop\MAIL2BUG\Mail_2_Bug_Repo\mail2bug\Mail2Bug\Email\EWS\EWSConnectionManger.cs:line 61
   at Mail2Bug.Email.MailboxManagerFactory.CreateMailboxManager(EmailSettings emailSettings) in C:\Users\mapar\Desktop\MAIL2BUG\Mail_2_Bug_Repo\mail2bug\Mail2Bug\Email\MailboxManagerFactory.cs:line 31
   at Mail2Bug.Mail2BugEngine..ctor(InstanceConfig configInstance, MailboxManagerFactory mailboxManagerFactory) in C:\Users\mapar\Desktop\MAIL2BUG\Mail_2_Bug_Repo\mail2bug\Mail2Bug\Mail2BugEngine.cs:line 31
   at Mail2Bug.PersistentInstanceRunner..ctor(InstanceConfig instanceConfig, MailboxManagerFactory mailboxManagerFactory) in C:\Users\mapar\Desktop\MAIL2BUG\Mail_2_Bug_Repo\mail2bug\Mail2Bug\InstanceRunner.cs:line 21
   at Mail2Bug.MainApp.InitInstances(IEnumerable`1 configs) in C:\Users\mapar\Desktop\MAIL2BUG\Mail_2_Bug_Repo\mail2bug\Mail2Bug\Main.cs:line 214
2017-05-29 14:53:48,971 [1] INFO  Mail2Bug.MainApp [(null)] - --------------- Iteration 0 ---------------
2017-05-29 14:53:49,989 [1] INFO  Mail2Bug.MainApp [(null)] - --------------- Iteration 1 ---------------
2017-05-29 14:53:50,997 [1] INFO  Mail2Bug.MainApp [(null)] - --------------- Iteration 2 ---------------

**Comment by nschonni** [comment] 2017-05-30 04:27
This looks like a duplicate of #64

**Comment by hershi** [comment] 2017-05-31 00:11
+1 on what @nschonni wrote.
In general, the error reported by EWS for authentication errors is misleading. 
I've updated the [Troubleshooting](https://github.com/Microsoft/mail2bug/wiki/Basic-Setup#common-errorstroubleshooting) section in the "Getting Started" guide to mention this specific error message - hopefully that helps people find it out on their own

**Closed by hershi** 2017-05-31 00:11 UTC
